#!/usr/bin/env python3
"""Generate the docs that should stay in sync with the repo on every commit.

Outputs (all under docs/, tracked in git):
  - docs/changelog.md         — from git history (newest first)
  - docs/reference/specs.md   — index of design specs (docs/superpowers/specs/*)
  - docs/reference/plans.md   — index of implementation plans (docs/superpowers/plans/*)

Pure standard library. Deterministic and idempotent — safe to run anytime.
Invoked automatically by .githooks/pre-commit; can also be run by hand:
    python3 scripts/gen_docs.py
"""
import subprocess
import pathlib


def repo_root() -> pathlib.Path:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"], text=True
        ).strip()
        return pathlib.Path(out)
    except Exception:
        return pathlib.Path(__file__).resolve().parents[1]


ROOT = repo_root()
DOCS = ROOT / "docs"


def first_heading(path: pathlib.Path) -> str:
    """First level-1 markdown heading, else the file stem."""
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            s = line.strip()
            if s.startswith("# "):
                return s[2:].strip()
    except Exception:
        pass
    return path.stem


def gen_index(subdir: str, title: str, outfile: str, blurb: str) -> int:
    """Write docs/reference/<outfile> indexing docs/superpowers/<subdir>/*.md."""
    src = DOCS / "superpowers" / subdir
    rows = []
    if src.is_dir():
        for p in sorted(src.glob("*.md"), reverse=True):
            name = p.name
            date = name[:10] if len(name) >= 10 and name[4] == "-" else ""
            rows.append((date, first_heading(p), f"../superpowers/{subdir}/{name}"))
    lines = [f"# {title}", "", blurb, ""]
    if rows:
        lines += ["| Date | Document |", "| --- | --- |"]
        lines += [f"| {d} | [{h}]({rel}) |" for d, h, rel in rows]
    else:
        lines.append("_None yet._")
    lines += ["", f"<small>Auto-generated by `scripts/gen_docs.py` — {len(rows)} documents.</small>", ""]
    out = DOCS / "reference" / outfile
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(rows)


def gen_changelog() -> int:
    """Write docs/changelog.md from git history, grouped by date (newest first)."""
    sep = "\x1f"
    try:
        raw = subprocess.check_output(
            ["git", "log", "--date=short", "--no-merges", f"--pretty=format:%h{sep}%ad{sep}%s"],
            text=True, cwd=str(ROOT),
        )
    except Exception:
        raw = ""
    lines = [
        "# Changelog", "",
        "Auto-generated from git history (newest first). "
        "Refreshed on every commit by the `.githooks/pre-commit` hook; merge commits are omitted.",
        "",
    ]
    cur_date = None
    count = 0
    for line in raw.splitlines():
        if not line.strip():
            continue
        parts = (line.split(sep) + ["", "", ""])[:3]
        h, date, subj = parts
        count += 1
        if date != cur_date:
            lines += ["", f"## {date}", ""]
            cur_date = date
        lines.append(f"- `{h}` {subj.replace('|', chr(92) + '|')}")
    lines += ["", f"<small>{count} commits.</small>", ""]
    (DOCS / "changelog.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return count


def main() -> None:
    (DOCS / "reference").mkdir(parents=True, exist_ok=True)
    s = gen_index("specs", "Design Specs",
                  "specs.md", "Every design spec in the repo, newest first. Each links to the full document.")
    p = gen_index("plans", "Implementation Plans",
                  "plans.md", "Every implementation plan in the repo, newest first.")
    c = gen_changelog()
    print(f"gen_docs: {s} specs, {p} plans, {c} commits")


if __name__ == "__main__":
    main()
